version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - '@angular/*'
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
